version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB = django_tutorial
      - POSTGRES_USER = bimbato
      - POSTGRES_PASSWORD = aevo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: